REM CONFIGURACION SSL
set SERVER_SSL_KEY_STORE_PASSWORD=8443
set SERVER_SSL_KEY_STORE_ALIAS=1
set SERVER_SSL_KEY_STORE_PASSWORD=Admin846*
set SERVER_SSL_KEY_STORE=borras.p12
set SERVER_SSL_KEY_STORE_TYPE=PKCS12

REM CONFIGURACION BASE
set DATABASE_SERVER=localhost
set DATABASE_DB_NAME=vgmdis
set DATABASE_USERNAME=unilever
set DATABASE_PASSWORD=costa2005

rem TOKEN
set TOKEN_JWT_SECRET=vGm2dm4n846*
set TOKEN_JWT_EXPIRA_ANIOS=30
set TOKEN_JWT_EXPIRA_DIAS=365
SET TOKEN_JWT_EXPIRA_HORAS=24
set TOKEN_JWT_EXPIRA_MINUTOS=60
set TOKEN_JWT_EXPIRA_SEGUNDOS=60

C:\Program Files\Java\jre1.8.0_251\bin\java -jar VGMInterface-0.0.1-SNAPSHOT.jar